# Generated by Django 4.2.1 on 2025-11-21 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='student.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='student',
            name='manual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod', to='student.manual', verbose_name='Manual'),
        ),
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='student.tagpost', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['time_create'], name='student_stu_time_cr_72028f_idx'),
        ),
    ]
